title: Shubham More
tagline: Shubham More
description: |
  Full Stack Developer with 2+ years experience in Node.js, Nuxt.js, and Express.js.
  Adept at building scalable web applications with a focus on optimizing RESTful APIs
  and server-side rendering (SSR) using Nuxt.js and Vue.js. Skilled in database management
  with MongoDB, ensuring seamless collaboration with UI/UX designers to produce visually
  stunning and user-centric interfaces. Proficient in implementing secure authentication
  protocols using JWT and Firebase Authentication, alongside dynamic image handling via AWS S3.
  Demonstrated expertise in e-commerce applications, multi-tenant architectures, payment
  gateway integrations, and real-time communication solutions. Combines technical prowess with
  a strong design sense to deliver solutions that emphasize user experience and security.
  Continually adapts and learns the latest technologies.

google_site_verification: JM_pjFgHafM30xeSObj9SZhB2eHCluzxNzYWweZOsXI

email: mores9785@gmail.com

baseurl: "/"
url: "https://more-shubham.github.io"
github_username:  more-shubham

sass:
  sass_dir: _sass

plugins:
  - jekyll-seo-tag

logo: https://more-shubham.github.io/favicon-32x32.png

author:
  name: Shubham More
  picture: https://more-shubham.github.io/Shubham-more.png
  url: https://more-shubham.github.io

social:
  name: Shubham More
  links:
    - https://more-shubham.github.io
    - https://shubham-more.com/
    - https://github.com/more-shubham
    - https://linkedin.com/in/dev-shubham-more
